name: CI
on: [push]
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master

            - name: Set Node.js 12.x
              uses: actions/setup-node@master
              with:
                  version: 12.x

            - name: yarn install
              run: yarn install

            - name: Verify
              run: yarn verify
